// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from "dotenv";
import { defineConfig } from "prisma/config";

loadEnv({ path: ".env.local" });
loadEnv();

function normalizePostgresUrl(value: string | undefined): string | undefined {
  if (!value) return value;

  const schemeMatch = value.match(/^(postgres(?:ql)?:\/\/)/i);
  if (!schemeMatch) return value;

  const scheme = schemeMatch[1];
  const authorityStart = scheme.length;
  const authorityEnd = value.indexOf("/", authorityStart);
  const safeAuthorityEnd = authorityEnd === -1 ? value.length : authorityEnd;
  const authority = value.slice(authorityStart, safeAuthorityEnd);
  const atIndex = authority.lastIndexOf("@");
  if (atIndex === -1) return value;

  const userInfo = authority.slice(0, atIndex);
  const hostInfo = authority.slice(atIndex + 1);
  const userSeparator = userInfo.indexOf(":");
  if (userSeparator === -1) return value;

  const username = userInfo.slice(0, userSeparator);
  let rawPassword = userInfo.slice(userSeparator + 1);

  // Support users pasting placeholder-style passwords like [my-password].
  if (rawPassword.startsWith("[") && rawPassword.endsWith("]")) {
    rawPassword = rawPassword.slice(1, -1);
  }

  let encodedPassword: string;
  try {
    encodedPassword = encodeURIComponent(decodeURIComponent(rawPassword));
  } catch {
    encodedPassword = encodeURIComponent(rawPassword);
  }

  const suffix = value.slice(safeAuthorityEnd);
  return `${scheme}${username}:${encodedPassword}@${hostInfo}${suffix}`;
}

process.env.DATABASE_URL = normalizePostgresUrl(process.env.DATABASE_URL);
process.env.DIRECT_URL = normalizePostgresUrl(process.env.DIRECT_URL);

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
});
