ALTER TABLE "Role"
  ADD COLUMN IF NOT EXISTS "isSystem" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "WorkLog"
  ALTER COLUMN "userId" DROP NOT NULL;

ALTER TABLE "WorkLog"
  DROP CONSTRAINT IF EXISTS "WorkLog_userId_fkey";

ALTER TABLE "WorkLog"
  ADD CONSTRAINT "WorkLog_userId_fkey"
  FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
